### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by armpomor** [dvk-net/deploy-django-app-postgresql-docker#1]
Сделал по вашему шаблону деплой небольшого мультиязычного сайта. Все получилось, все работает (https, static, media, db и т.д.)  за исключением переключения языков (переводится только динамика, но не статика) и отправки сообщения из контактной формы. При переключении языков переводится только динамика из базы данных, но не статика, а при отправке сообщения из контактной формы ошибка 502 Bad Gateway в логах nginx при этом "[error] 10#10: *92 upstream prematurely closed connection while reading response header from upstream".

**Comment by dvk-net** [comment]
Надо смотреть логи nginx и gunicorn

**Comment by armpomor** [comment]
С отправкой писем разобрался,  был закрыт 465 порт на сервере, теперь сообщения отправляются. Все работает.

**Comment by dvk-net** [comment]
Ну отлично!
